### ISSUE TITLE
[BUG] terramate run --changed fails with "is not a git repository"

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [terramate-io/terramate#1159] opened 2023-09-22 12:49 UTC
**Describe the bug**
When running `terramate list --changed` or `terramate run --changed -- ...` as a step on github actions it results with: 
`FTL computing selected stacks: listing changed stacks error: the path "/__w/repo-name/repo-name" is not a git repository`
even `git rev-parse --show-toplevel` shows correct `/__w/repo-name/repo-name`

Adding `--log-level=trace` doesn't give much more information as [terramate](https://github.com/terramate-io/terramate/blob/main/git/git.go#L815) doesn't print out the command and other parameters. `IsRepository()` function never prints out the error message.

Strange thing is that it happens only when using github actions with `container:` option... where I checkout the code and run the commands inside a container with preinstalled terramate and terraform.

If I use plain `ubuntu-latest` github runner and install terramate and terraform during github actions the issue doesn't appear :/

**Expected behavior**
Github repository check works as expected and in case of errors they are printed out

**Log Output**
```
$ git status
On branch SRE-195-terramate
Your branch is up to date with 'origin/SRE-195-terramate'.

nothing to commit, working tree clean
```
```
$ terramate experimental get-config-value 'terramate'
{
  root = {
    path = {
      fs = {
        absolute = "/__w/repo-name/repo-name"
        basename = "repo-name"
      }
    }
  }
  stacks = {
    list = ["/terramate/stacks/prod/loki-gcs", "/terramate/stacks/staging/loki-gcs"]
  }
  version = "0.4.1"
}
```
```
$ terramate list --log-level=trace --changed
...
2023-09-22T11:39:40Z TRC Create cmd to execute action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC Append arguments action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC Running git command action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC git command executed with success action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC Check if path is git repo. action=ListChanged()
2023-09-22T11:39:40Z TRC Create cmd to execute action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC Append arguments action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z TRC Running git command action=Git.exec() workingDir=/__w/repo-name/repo-name
2023-09-22T11:39:40Z FTL listing stacks: listing changed stacks error: the path "/__w/repo-name/repo-name" is not a git repository
```

**Environment (please complete the following information):**
 - Ubuntu 22.04.3 LTS
 - git 2.34.1
 - terramate 0.4.1

**Comment by soerenmartius** [comment] 2023-09-22 13:13
Hi @pwilczynskiclearcode,

Thanks for reporting this, we will look at this issue shortly and get back to you.

> Adding --log-level=trace doesn't give much more information as [terramate](https://github.com/terramate-io/terramate/blob/main/git/git.go#L815) doesn't print out the command and other parameters. IsRepository() function never prints out the error message.

This is a valid point. We are working on more comprehensive outputs already since this has been requested by the community multiple times before.

Thanks!

**Comment by i4ki** [comment] 2023-09-22 13:29
Hey @pwilczynskiclearcode 

can you share a simplified version of this GHA container config? so I can reproduce it here.
Thank you for reporting it.

**Comment by pwilczynskiclearcode** [comment] 2023-09-22 13:50
Dockerfile looks like:
```Dockerfile
FROM	ubuntu:22.04	AS	base
RUN	apt update -y \
	&& apt install -yqq curl git unzip \
	&& rm -rf /var/lib/apt/lists/*

FROM	base	AS	download-stage

RUN	curl -L "https://github.com/terramate-io/terramate/releases/download/v0.4.1/terramate_0.4.1_linux_x86_64.tar.gz" | tar xvz -C /tmp/ \
	&& mv /tmp/terramate /tmp/terramate-ls /opt/
RUN	chmod +x /opt/*

FROM	base
COPY	--from=download-stage --chown=0:0 --link /opt/ /usr/local/bin/
RUN	 terramate install-completions
```
(I stripped terraform and other stuff that we use but it should be sufficient to be tested.


and github workflow looks like:
```
name: Verify terraform changes

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master

jobs:
  verify-terraform:
    name: Verify terraform changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user 0:0
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true

      - name: Git config
        # This is due to an open issue with github-actions runner
        # tracked at <https://github.com/actions/runner/issues/2033>
        run: |
          git config --global --add safe.directory '*'

      - name: Check Terraform Formatting
        run: terraform fmt -recursive -check -no-color

      - name: Check Terramate Formatting
        run: terramate fmt --check

      - name: Initialize Stacks
        run: |
          terramate run --changed-- terraform init
     
```

**Comment by i4ki** [comment] 2023-09-22 17:13
Hi @pwilczynskiclearcode 

Thanks for the additional information. I reproduced it here and we have a fix already. Just adding some tests now. It will be included in the next release.
Thank you very much!

**Comment by i4ki** [comment] 2023-09-27 22:19
Hi @pwilczynskiclearcode 

I will give more information on why this issue has not been resolved yet.

In Terramate we have two `git` _wrappers_, one in the frontend/cli part and another in the core change detection feature. 

The cli git wrapper invokes `git` with the user's environment variables and then the global and local/user config is loaded and then it recognizes the system's config (repo `.git/config`, `$HOME/.gitconfig`, etc). Then the cli detects that the project is inside a repository and enables the change detection features (eg.: `--changed`). So in your case, the `safe.directory` option recognized at this layer and git is happy.

The core git wrapper invokes `git` completely isolated and the reason for that is that git config can change git behavior (even for *git plumbing commands*) and then if we allowed the load of git user config we would receive bug reports heavily dependent on the user's environment. In your case, that's why just later on the `git` commands start to fail because `git` complains about the ownership mismatch of the files (the `safe.directory` is not set).

We discussed it internally and we are still not sure about what is the best option here, because just allowing the user's env could have a big impact and lead to more issues.

One idea that was discussed was adding a configuration to the `.terramaterc` file where users can customize the core change detection git wrapper, for example:

```
# ~/.terramaterc
git {
    config {
        "safe.directory" = "*"
        # other options
    }
}
```

and then the core `git` wrapper will execute still isolated but we explicitly set this config in the cmd line:

```
git -c 'safe.directory=*' diff-tree ...
```

This setup of invoking Terramate inside docker but mapping the cloned files from the host is currently problematic, but doable, because it requires specific docker options to guarantee the files generated by Terramate match the permission/ownership of the host user.

Additionally, we never tested Terramate inside docker containers and frankly, we don't use this setup internally, so it's possible that you will encounter more issues along the way if trying to invoke Terramate in it.

We plan to add full support for running Terramate in containers soon and then have it all documented.

**Comment by pwilczynskiclearcode** [comment] 2023-10-01 14:10
@i4ki 
Thank you. I was forced to install terramate during workflow run and I use [`asdf-vm/actions/install`](https://github.com/terramate-io/terramate-github-actions-example/blob/main/.github/workflows/plan.yml#L23-L24) action which is fast and good enough for now.

**Closed** 2023-11-06 15:42 UTC
Labels: bug
