### ISSUE TITLE
[FEATURE] Use "#" for comments instead of "//"

### ISSUE THREAD

**Issue by cwe1ss** [terramate-io/terramate#1310] opened 2023-12-20 07:52 UTC
**Is your feature request related to a problem? Please describe.**
[HashiCorp recommends](https://developer.hashicorp.com/terraform/language/syntax/configuration#comments) to use "#" for comments, but Terramate is using "//" [for its marker-comment](https://github.com/terramate-io/terramate/blob/50537c2abd4aae353b29a8313aa5acd986c585be/generate/genhcl/genhcl.go#L44). By doing so, we can no longer use tools like TFLint that contain [rules to enforce consistent comments](https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_comment_syntax.md).

**Describe the solution you'd like**
Either fully switch to using "#" for Terramate-internal comments (which could be considered a breaking change since it marks all generated files as changed), or allow us to set the comment style in the terramate config-block.

**Describe alternatives you've considered**
The alternative is to completely disable the linting rules, which does not allow us to use consistent comment styles in our projects.

**Comment by soerenmartius** [comment] 2024-01-08 12:46
Hi @cwe1ss, thanks for reporting this. I am going to close this issue as it's a duplicate of #1213 and will provide more context in #1213 also. Again, thanks for reporting this - we're working on a solution!

**Comment by cwe1ss** [comment] 2024-01-08 14:06
If I understand your code correctly, I don't believe this is related to #1213. This issue is about the [very first line that you hard-code into every generated tf-file](https://github.com/terramate-io/terramate-examples/blob/845db161b5c89f3dfd2df300450a1f9fd3e3f99b/01-keep-terraform-dry/stacks/a-stack/_terramate_generated_backend.tf#L1). Since [you seem to add this to the file via a regular string](https://github.com/terramate-io/terramate/blob/50537c2abd4aae353b29a8313aa5acd986c585be/generate/genhcl/genhcl.go#L94), it shouldn't depend on the HCL writer. 

#1213 is about comments that we would add to our own `generate_hcl.content`-block and should be preserved in the generated files (which is an important request as well).

**Comment by soerenmartius** [comment] 2024-01-10 07:27
> If I understand your code correctly, I don't believe this is related to #1213. This issue is about the [very first line that you hard-code into every generated tf-file](https://github.com/terramate-io/terramate-examples/blob/845db161b5c89f3dfd2df300450a1f9fd3e3f99b/01-keep-terraform-dry/stacks/a-stack/_terramate_generated_backend.tf#L1). Since [you seem to add this to the file via a regular string](https://github.com/terramate-io/terramate/blob/50537c2abd4aae353b29a8313aa5acd986c585be/generate/genhcl/genhcl.go#L94), it shouldn't depend on the HCL writer.
> 
> #1213 is about comments that we would add to our own `generate_hcl.content`-block and should be preserved in the generated files (which is an important request as well).

that's correct - sorry I missread this in the first place. Let me bring this to team the once again and get back to you.

**Comment by mariux** [comment] 2024-01-25 22:16
We will allow to configure the format in one of the next releases.

`terramate.config.generate.hcl_magic_header_comment_style` will be available soon to switch from the default `//` to `#` comments.

**Closed** 2024-02-09 12:32 UTC
Labels: enhancement
