### ISSUE TITLE
TestGitGlobalConfigIsUsed is failing

### ISSUE THREAD

**Issue by serdardalgic** [terramate-io/terramate#1431] opened 2024-02-07 14:09 UTC
**Describe the bug**

I'm not so sure if it's because of my local configuration, but the tests are failing on my local machine, particularly 
```
FAIL	github.com/terramate-io/terramate/cmd/terramate/e2etests/core	161.297s
```

**To Reproduce**
```
make test
```
or, to be more specific:
```
/opt/homebrew/bin/go test -timeout 30s -run ^TestGitGlobalConfigIsUsed$ github.com/terramate-io/terramate/cmd/terramate/e2etests/core
```
please adjust your go path according while running that test. 

**Expected behavior**
tests pass

**Log Output**
```
2024/02/07 13:41:56 Terraform detected version: 1.5.7
toolsetPath: /var/folders/ff/jhj4yfd11v7fxgxc399_pwb80000gn/T/cmd-terramate-test-3290365609
--- FAIL: TestGitGlobalConfigIsUsed (4.37s)
    list_git_test.go:368: config: [core]
        	excludesfile = /private/var/folders/ff/jhj4yfd11v7fxgxc399_pwb80000gn/T/tm-tmpdir628055803/terramate-test3689094527/sandbox/.gitignore
    list_git_test.go:369: ignore: *.test
    list_git_test.go:389: "run /var/folders/ff/jhj4yfd11v7fxgxc399_pwb80000gn/T/cmd-terramate-test-3290365609/helper true" stderr="terramate: Entering stack in /stack
        terramate: Executing command "/var/folders/ff/jhj4yfd11v7fxgxc399_pwb80000gn/T/cmd-terramate-test-3290365609/helper true"
        " does not match regex "repository has untracked files"
    list_git_test.go:389: wanted[1] but got[0]: exit status mismatch
FAIL
FAIL	github.com/terramate-io/terramate/cmd/terramate/e2etests/core	161.297s
```

**Environment (please complete the following information):**
OS: Darwin arm64
OS Version Darwin Kernel Version 23.2.0 - MacOs Sonoma 14.2.1
Git Version 2.43.0
Terramate Version 0.4.4

**Additional context**
```
% /opt/homebrew/bin/go version
go version go1.21.4 darwin/arm64
```
ask if needed

**Comment by i4ki** [comment] 2024-02-09 17:16
Hi @serdardalgic 

I still don't know what could be the root cause of this failing test but we will investigate.
Thanks for letting us know.

I will remove the `bug` label for now unless you can confirm this problem is not only in the tests.

**Comment by mariux** [comment] 2024-04-17 15:07
i am closing the issue as we can nor reproduce the failing test and no feedback has been received for a while. please feel free to re-open when the issue still keeps showing.

**Closed by mariux** 2024-04-17 15:07 UTC
