### ISSUE TITLE
[BUG] Output sharing: sensitive attribute missing in generated files

### ISSUE THREAD

**Issue by apweisskopf** [terramate-io/terramate#1916] opened 2024-10-12 11:37 UTC
**Describe the bug**
When utilizing the experimental "outputs sharing" feature in Terramate, we are encountering an issue where the `sensitive` attribute defined in the `output` block is not being propagated to the generated sharing files.

According to the documentation, you can specify the `sensitive` attribute in the output block to indicate if the output value is sensitive. However, after running the `terramate generate`, the generated files do not include this attribute.

**To Reproduce**
`stack.tm.hcl`

```
output "password" {
  backend   = "default"
  value     = random_password.password.result
  sensitive = true
}
```

This generates the following `_tm_generated_sharing.tf` file

```
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT

output "password" {
  value = random_password.password.result
}
```

The attribute `sensitive` is missing in the output block.

**Expected behavior**
```
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT

output "password" {
  value = random_password.password.result
  sensitive = true
}
```

**Environment:**
 - OS: MacOS
 - OS Version: 15.0.1
 - Git Version: 2.47.0
 - Terramate Version: 0.10.7

**Additional context**
Looking at the code it seems that emitting the `sensitive` attribute when generating the output sharing block is missing

https://github.com/terramate-io/terramate/blob/e300b2fc2ee8d877625a8c10e546e4d46fbf4eee/generate/sharing/sharing_backend.go#L51-L54

When further looking at the code it seems that the default for `sensitive` is `true`. We would rather prefer when there is no `sensitive` flag set in the sharing block, neither a `sensitive` `true` nor `false` block should be generated.

See
https://github.com/terramate-io/terramate/blob/e300b2fc2ee8d877625a8c10e546e4d46fbf4eee/config/sharing_backend.go#L49
and
https://github.com/terramate-io/terramate/blob/e300b2fc2ee8d877625a8c10e546e4d46fbf4eee/config/sharing_backend.go#L97

**Comment by soerenmartius** [comment] 2024-10-12 17:19
Thanks for reporting this @apweisskopf! We just reproduced this on our end and will start working on a fix right away.

**Comment by i4ki** [comment] 2024-10-14 14:57
Fixed in [`v0.10.8`](https://github.com/terramate-io/terramate/releases/tag/v0.10.8).

Thanks @apweisskopf !

**Closed by i4ki** 2024-10-14 14:57 UTC
Labels: bug, planned

**Comment by i4ki** [comment] 2024-10-14 21:27
Hi @apweisskopf,

Indeed the sensitive attribute is optional but it was designed to be true by default. The bug was that it was not being generated and only this was fixed.

Keep in mind that this feature is still experimental, and it's not our recommended approach for sharing values between stacks. As we work towards a more stable design, you can expect some breaking changes.

The rationale behind making it `sensitive` by default is to reduce the risk of unintentionally exposing secrets. This way, users must explicitly indicate if a value is not sensitive.

Maybe the `sharing_backend` block can have a `default_sensititity = false/true`  which controls the default value of its `input` and `output` blocks. What do you think?

**Comment by i4ki** [comment] 2024-10-15 12:08
Hi @apweisskopf 

> Good to know, then I somehow misinterpreted the documentation.

The documentation was lacking, sorry. I'm updating it here: https://github.com/terramate-io/terramate-docs/pull/102

I will share your thoughts about the default value with the rest of the team and come back to you soon.
Thanks for the help!

**Comment by i4ki** [comment] 2024-10-15 17:25
Hey @apweisskopf 

We discussed your feedback and we agreed that makes sense to follow OpenTofu/Terraform behavior here because the sensitivity of values are tracked and so the user will be warned anyway if mistakenly passing a sensitive value around.

In the next release we will change the behavior to only generate the `sensitive` attribute if it's set by the user (no default value).

Sorry for the back and forth and thank you again for taking the time to explain your case.

**Comment by i4ki** [comment] 2024-10-17 16:00
thank you for checking!!
I will release v0.10.9 now!
